# -*- coding: utf-8 -*-
"""PengukuranCitra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MCv6lr4CAsQ3KdSvI-HUZQLD-CP2EZ-O
"""

!pip install opencv-python

!pip install numpy

!pip install matplotlib

import numpy as np
from PIL import Image

def calculate_mse(image1, image2):
    return np.mean((image1 - image2) ** 2)

def calculate_psnr(mse, max_pixel=255.0):
    return 20 * np.log10(max_pixel / np.sqrt(mse))

# Load dua gambar untuk perhitungan MSE
image1 = Image.open('p1.png').convert('L')  # Sesuaikan path dengan lokasi gambar Anda
image2 = Image.open('p2.png').convert('L')  # Sesuaikan path dengan lokasi gambar Anda

# Pastikan kedua gambar memiliki dimensi yang sama
image1 = image1.resize(image2.size)

# Konversi gambar ke array NumPy
image1_array = np.array(image1)
image2_array = np.array(image2)

# Hitung nilai MSE
mse = calculate_mse(image1_array.astype(float), image2_array)
print(f'Mean Squared Error (MSE): {mse}')

# Hitung nilai PSNR
psnr = calculate_psnr(mse)
print(f'Peak Signal-to-Noise Ratio (PSNR): {psnr} dB')