# -*- coding: utf-8 -*-
"""stegano.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xgdyakDKexh-rMrQz0OtzuQb_dfCP5oc
"""

!pip install stegano

from stegano import lsb

secret = lsb.hide("p1.png", "halo saya leman, ini adalah pesan yang saya ingin sampaikan kepada kamu")
secret.save("p1.png")
#print(lsb.reveal("p1.png"))

from stegano import lsb

#secret = lsb.hide("patrick.png", "halo saya leman, ini adalah pesan yang saya ingin sampaikan kepada kamu")
#secret.save("p1.png")
print(lsb.reveal("p1.png"))

from google.colab import drive
drive.mount('/content/drive')

